### read all users
GET http://localhost:4000/user/test

###read user by objectid
GET http://localhost:4000/user/users/697dbc744ba08436135f06c9

###create user
POST http://localhost:4000/user/create
Content-Type: application/json

{
    "username":"abhi",
    "password":"abhi123",
    "age":18
}

###update user
PUT http://localhost:4000/user/update/697dbc744ba08436135f06c9
Content-Type: application/json

{
    "username":"abhi",
    "password":"abhi123",
    "age":19
}

### Delete user by objectid
DELETE http://localhost:4000/user/delete/697dbc744ba08436135f06c9

###product API
GET http://localhost:4000/product/products

###read user by obectid
GET http://localhost:4000/product/products/697dd1e0be680faad965292f

###create product

POST http://localhost:4000/product/create
Content-Type: application/json

{
    "productid":"123",
    "name":"pen",
    "price":"12345",
    "brand":"meow"

    
}

###update product

PUT http://localhost:4000/product/update/697dd1e0be680faad965292f
Content-Type: application/json

{
    "productid":"1234",
    "name":"pen",
    "price":"12345",
    "brand":"meow"
}

###delete product

DELETE http://localhost:4000/product/delete/697dd1e0be680faad965292f


### login user
POST http://localhost:4000/user/auth
Content-Type: application/json

{
    "username": "abhi",
    "password": "abhi123"
}


###req for protected routes
GET http://localhost:4000/user/test

###test
GET http://localhost:4000/user/test

